---
apiVersion: v1
kind: Service
metadata:
  name: kaos-operator
  namespace: kube-system
  labels:
    app: kaos-operator
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: kaos-operator

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: kube-system
  name: kaos-operator
spec:
  selector:
    matchLabels:
      app: kaos-operator
  serviceName: kaos-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: kaos-operator
    spec:
      serviceAccountName: kaos-operator
      containers:
      - name: kaos-operator
        image: arnaudmz/kaos:v0.4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          name: http
